[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "v22.14.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200